name: Java 23 CI/CD Pipeline

on:
  push:
    branches:
      - Gameplay
      - handika/ci-setup
      - States

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '23'
          cache: maven

      - name: Clean previous build
        run: mvn clean package

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test

      - name: Generate Javadoc
        run: mvn javadoc:javadoc
